version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: medicalcare-postgres
    environment:
      POSTGRES_DB: medicalcare_db
      POSTGRES_USER: medicalcare_user
      POSTGRES_PASSWORD: medicalcare_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - medicalcare-network

  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: medicalcare-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medicalcare_db
      SPRING_DATASOURCE_USERNAME: medicalcare_user
      SPRING_DATASOURCE_PASSWORD: medicalcare_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - medicalcare-network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medicalcare-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - medicalcare-network

volumes:
  postgres_data:

networks:
  medicalcare-network:
    driver: bridge 